# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-file_fixtures/all/rspec-file_fixtures.rbi
#
# rspec-file_fixtures-0.1.6

module RSpecFileFixtures
  def fixture(path); end
end
class RSpecFileFixtures::Fixture
  def base_path; end
  def from_json(symbolize_names_shorthand = nil, symbolize_names: nil); end
  def from_xml; end
  def from_yaml(symbolize_names_shorthand = nil, symbolize_names: nil); end
  def from_yml(symbolize_names_shorthand = nil, symbolize_names: nil); end
  def initialize(raw_path); end
  def json(symbolize_names_shorthand = nil, symbolize_names: nil); end
  def method_missing(method_name, *args); end
  def path; end
  def pathname; end
  def read; end
  def respond_to_missing?(method_name, _ = nil); end
  def xml; end
  def yaml(symbolize_names_shorthand = nil, symbolize_names: nil); end
  def yml(symbolize_names_shorthand = nil, symbolize_names: nil); end
end
class RSpecFileFixtures::Error < StandardError
end
