# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/stash-rewards/all/stash-rewards.rbi
#
# stash-rewards-0.0.3

module Stash
end
module Stash::Rewards
end
class Stash::Rewards::Error < StandardError
end
