name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5

    steps:
    - uses: actions/checkout@v1

    - name: Gem cache
      id: cache-bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}

    - name: Bundle install
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle

    - name: Run tests
      run: |
        bundle exec rspec
